### ISSUE TITLE
new version of pip

### ISSUE THREAD

**Issue by aenbar** [learn-co-curriculum/py-lists-with-maps#1]
this shows up when you run '!pip install folium'

You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

not clear whether we should do anything with that information (install? ignore?)

**Comment by aturkewi** [comment]
Just adding a note to this issue. 

I was talking to some one who has recently started going through and he felt some confusion around this.

**Comment by AdamWeissman** [comment]
It now says:

You are using pip version 10.0.1, however version 19.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

...going to try to see if it works without upgrading first, if it doesn't work, will try to upgrade.
