### ISSUE TITLE
Stuck on List with Maps

### ISSUE THREAD

**Issue by AnneByrne1984** [learn-co-curriculum/py-lists-with-maps#10]
Hi,

I'm currently having an issue with the list with maps, and I really don't know how to proceed. Rather than continue to hunt and peck, can someone please help me either re-set the lab or help me figure out how to do it?

Thanks, 

Anne

**Comment by ALHep009** [comment]
palermo = None  #Given in the example, we had to assign palermo to the first value in our list
palermo = neighborhoods[0]
print(palermo)

This was how I began with trying the assignment. I'm sorry that it took so long for someone to answer this, it gave me trouble for a while as well.
