### ISSUE TITLE
TypeErrorTraceback (most recent call last)

### ISSUE THREAD

**Issue by RacheLily** [learn-co-curriculum/py-lists-with-maps#11]
import folium
buenos_map = folium.Map([ba_latitude, ba_longitude])
buenos_map

TypeErrorTraceback (most recent call last)
<ipython-input-19-82ab50141306> in <module>()
      1 import folium
----> 2 buenos_map = folium.Map([ba_latitude, ba_longitude])
      3 buenos_map

**Comment by mas16** [comment]
Hi RacheLily, thanks for the note! This looks like an error with how ba_latitude and la_longitude are defined. Double check that they are what you want them to be and run again.
