### ISSUE TITLE
Folium map not rendering in "Lists with Maps" section of Data Science Bootcamp Prep

### ISSUE THREAD

**Issue by dctom** [learn-co-curriculum/py-lists-with-maps#13]
![screenshot 2019-01-26 at 12 09 33 - display 2](https://user-images.githubusercontent.com/46691289/51790432-4c792f00-2163-11e9-995c-2271a66c1ed2.png)

**Comment by rdoyle101** [comment]
I'm also having this issue.
<img width="598" alt="Screen Shot 2019-04-02 at 8 56 04 AM" src="https://user-images.githubusercontent.com/49043664/55404096-31d98280-5525-11e9-9f80-058f147781ab.png">

**Comment by sheinsoe** [comment]
![Screen Shot 2019-04-03 at 19 57 35](https://user-images.githubusercontent.com/49161144/55505414-f8029c00-564a-11e9-8cab-779c8633941f.png)

and then, if you Press shift + enter on every cell, it should be fine, hope it this help
