### ISSUE TITLE
Map won't appear

### ISSUE THREAD

**Issue by houssamjouni** [learn-co-curriculum/py-lists-with-maps#8]
Hello Team

Kindly note that the map in this lab lesson is  coming up completely grey, there is no content.
Would you be able to advise me of the best way to fix this issue/workaround?

Kind Regards
Houssam Jouni

**Comment by joanrig** [comment]
Yes, I am experiencing the same thing. Made triple sure to click shift+enter on all code cells and map is rendering as one big grey (empty) box.
