### ISSUE TITLE
`!pip install folium` command not working

### ISSUE THREAD

**Issue by hansenjl** [learn-co-curriculum/py-lists-with-maps#9]
I get the following error when I try to run `!pip install folium`

```
sh: 0: getcwd() failed: No such file or directory
The folder you are executing pip from can no longer be found.
```

This results in the next commands not working. Do I need to install something locally on my computer for this to work?

**Comment by miaiseman** [comment]
I think this is something that the Learn.co side of things needs to install, not the users. Just my first instinct, could be wrong.
